[theme]
base = "dark"
# Color Palette
primaryColor = "#5FA8FF"  # More accessible blue with better contrast
backgroundColor = "#0F172A"  # Deep navy base (WCAG AAA compliant)
secondaryBackgroundColor = "#1E293B"  # Contrasting layer
textColor = "#F8FAFC"  # Soft white for reduced eye strain
font = "sans serif"

# Enhanced Component Styling
[theme.componentStyles]
button = """
    background-color: #5FA8FF;
    color: #0F172A;
    border-radius: 8px;
    padding: 0.75rem 1.5rem;
    &:hover { background-color: #478DE6; }
"""
input = """
    border-radius: 6px;
    border: 1px solid #334155;
    &:focus { box-shadow: 0 0 0 2px #5FA8FF; }
"""

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200  # In MB

### Design Rationale ###
# 1. Color System:
#    - Primary: #5FA8FF (better luminosity ratio)
#    - Background: NASA-style dark theme for long sessions
#    - Success/Danger states added for better system feedback

# 2. Typography:
#    - Modern sans-serif stack
#    - Clear hierarchy through font weights

# 3. Components:
#    - Consistent border radius (8px)
#    - Interactive states with hover effects
#    - Focus indicators for accessibility

# 4. Safety:
#    - XSRF protection enabled
#    - Reasonable upload size limit

# To use: Save as .streamlit/config.toml and restart app